### ISSUE TITLE
Add 2020 Keyesville Classic

### ISSUE THREAD

**Issue by shgysk8zer0** [kernvalley/events.kernvalley.us#53]
Find all relevant info for this year, including price, and create the event.

**Comment by shgysk8zer0** [comment]
Facebook event [here](https://www.facebook.com/events/1292240120981119/)

**Comment by hungryfat92** [comment]
Okay how do I make the branch in reference to an issue again?

**Comment by shgysk8zer0** [comment]
So much easier to show you.

I cannot just give a step by step guide because you're working off a fork, which is different in one significant way.
